<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UserProfileSeeder extends Seeder
{
    /**
     * Seed the user_profiles table.
     *
     * @return void
     */
    public function run()
    {
        // Insert user profile for admin user
        DB::table('user_profile')->insert([
            [
                'last_name' => 'Admin',
                'first_name' => 'Admin',
                'middle_initial' => null,
                'license_number' => null,
                'address' => 'Admin Address',
                'date_of_birth' => '1980-01-01',
                'sex' => 'Male',
                'contact_number' => '1234567890',
                'contact_person' => 'John Doe',
                'contact_person_number' => '0987654321', 
                'user_profile_image' => null,
                'position' => 'operation_manager',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'off_duty',
            ],
            [
                'last_name' => 'Admin2',
                'first_name' => 'Admin2',
                'middle_initial' => null,
                'license_number' => null,
                'address' => 'Admin2 Address',
                'date_of_birth' => '1980-01-01',
                'sex' => 'Male',
                'contact_number' => '1234567890',
                'contact_person' => 'John Doe',
                'contact_person_number' => '0987654321', 
                'user_profile_image' => null,
                'position' => 'operation_manager',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'off_duty',
            ],
            [
                'last_name' => 'Dispatcher',
                'first_name' => 'Dispatcher',
                'middle_initial' => null,
                'license_number' => null,
                'address' => 'Dispatcher Address',
                'date_of_birth' => '1980-01-01',
                'sex' => 'Male',
                'contact_number' => '1234567890',
                'contact_person' => 'John Doe',
                'contact_person_number' => '0987654321', 
                'user_profile_image' => null,
                'position' => 'dispatcher',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'off_duty',
            ],
            [
                'last_name' => 'Dispatcher2',
                'first_name' => 'Dispatcher2',
                'middle_initial' => null,
                'license_number' => null,
                'address' => 'Dispatcher2 Address',
                'date_of_birth' => '1980-01-01',
                'sex' => 'Male',
                'contact_number' => '1234567890',
                'contact_person' => 'John Doe',
                'contact_person_number' => '0987654321', 
                'user_profile_image' => null,
                'position' => 'dispatcher',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'off_duty',
            ],

            // 5 drivers
            [
                'last_name' => 'Driver1',
                'first_name' => 'John',
                'middle_initial' => 'A',
                'license_number' => 'D123456789',
                'address' => '123 Driver Street',
                'date_of_birth' => '1990-05-10',
                'sex' => 'Male',
                'contact_number' => '09123456789',
                'contact_person' => 'Jane Doe',
                'contact_person_number' => '09876543210', 
                'user_profile_image' => null,
                'position' => 'driver',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],
            [
                'last_name' => 'Driver2',
                'first_name' => 'Mary',
                'middle_initial' => 'B',
                'license_number' => 'D987654321',
                'address' => '456 Driver Avenue',
                'date_of_birth' => '1992-07-22',
                'sex' => 'Female',
                'contact_number' => '09123456780',
                'contact_person' => 'James Doe',
                'contact_person_number' => '09876543211', 
                'user_profile_image' => null,
                'position' => 'driver',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],
            [
                'last_name' => 'Driver3',
                'first_name' => 'Peter',
                'middle_initial' => 'C',
                'license_number' => 'D112233445',
                'address' => '789 Driver Lane',
                'date_of_birth' => '1985-06-10',
                'sex' => 'Male',
                'contact_number' => '09123456781',
                'contact_person' => 'Sara Doe',
                'contact_person_number' => '09876543212', 
                'user_profile_image' => null,
                'position' => 'driver',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],
            [
                'last_name' => 'Driver4',
                'first_name' => 'Samantha',
                'middle_initial' => 'D',
                'license_number' => 'D556677889',
                'address' => '1234 Main Street',
                'date_of_birth' => '1993-02-25',
                'sex' => 'Female',
                'contact_number' => '09123456782',
                'contact_person' => 'David Doe',
                'contact_person_number' => '09876543213', 
                'user_profile_image' => null,
                'position' => 'driver',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],
            [
                'last_name' => 'Driver5',
                'first_name' => 'Chris',
                'middle_initial' => 'E',
                'license_number' => 'D667788990',
                'address' => '5677 New Road',
                'date_of_birth' => '1991-04-15',
                'sex' => 'Male',
                'contact_number' => '09123456783',
                'contact_person' => 'Emma Doe',
                'contact_person_number' => '09876543214', 
                'user_profile_image' => null,
                'position' => 'driver',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],

            // 5 passenger_assistant_officer
            [
                'last_name' => 'Assistant1',
                'first_name' => 'Tom',
                'middle_initial' => 'A',
                'license_number' => null,
                'address' => '123 Assistant Street',
                'date_of_birth' => '1995-03-14',
                'sex' => 'Male',
                'contact_number' => '09123456784',
                'contact_person' => 'Sarah Doe',
                'contact_person_number' => '09876543215', 
                'user_profile_image' => null,
                'position' => 'passenger_assistant_officer',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],
            [
                'last_name' => 'Assistant2',
                'first_name' => 'Linda',
                'middle_initial' => 'B',
                'license_number' => null,
                'address' => '456 Assistant Avenue',
                'date_of_birth' => '1993-08-19',
                'sex' => 'Female',
                'contact_number' => '09123456785',
                'contact_person' => 'Michael Doe',
                'contact_person_number' => '09876543216', 
                'user_profile_image' => null,
                'position' => 'passenger_assistant_officer',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],
            [
                'last_name' => 'Assistant3',
                'first_name' => 'Robert',
                'middle_initial' => 'C',
                'license_number' => null,
                'address' => '789 Assistant Boulevard',
                'date_of_birth' => '1994-12-30',
                'sex' => 'Male',
                'contact_number' => '09123456786',
                'contact_person' => 'Emily Doe',
                'contact_person_number' => '09876543217', 
                'user_profile_image' => null,
                'position' => 'passenger_assistant_officer',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],
            [
                'last_name' => 'Assistant4',
                'first_name' => 'Anna',
                'middle_initial' => 'D',
                'license_number' => null,
                'address' => '101 Assistant Lane',
                'date_of_birth' => '1996-09-12',
                'sex' => 'Female',
                'contact_number' => '09123456787',
                'contact_person' => 'John Doe',
                'contact_person_number' => '09876543218', 
                'user_profile_image' => null,
                'position' => 'passenger_assistant_officer',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ],
            [
                'last_name' => 'Assistant5',
                'first_name' => 'Paul',
                'middle_initial' => 'E',
                'license_number' => null,
                'address' => '202 Assistant Road',
                'date_of_birth' => '1997-11-22',
                'sex' => 'Male',
                'contact_number' => '09123456788',
                'contact_person' => 'Karen Doe',
                'contact_person_number' => '09876543219', 
                'user_profile_image' => null,
                'position' => 'passenger_assistant_officer',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'date_hired' => Carbon::now(),
                'status' => 'on_duty',
            ]
        ]);
    }
}
